name: Deploy Storybook to GitHub Pages

on:
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: github-pages
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        include:
          - angular-version: 17
            node-version: '20.19.0'
          - angular-version: 16
            node-version: '18.20.8'
          - angular-version: 15
            node-version: '18.19.0'
          - angular-version: 14
            node-version: '16.20.0'
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm

      - name: Apply Angular version dependencies
        run: node scripts/use-angular-version.mjs ${{ matrix.angular-version }}

      - name: Install dependencies (Old angular packages have peer dependency issues, so using --legacy-peer-deps)
        run: npm install --no-package-lock --legacy-peer-deps

      - name: Build Angular library
        run: npx ng build ng-swiper-element

      - name: Build Storybook
        run: npm run build-storybook

      - name: Deploy this version to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./storybook-static
          publish_branch: gh-pages
          destination_dir: v${{ matrix.angular-version }}
          keep_files: true